image: node latest

stages:
  - build
  - deploy

build:
  stage: build
  before-script:
    - sudo apt install yarn
  script:
    - echo "building from src"
    - yarn -v
    - yarn install
    - yarn run build
