image: node:lastest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

before_script:
    - apt-get update -qq && apt-get install -qy libelf1

build:
  stage: build
  before_script:
    - npm -v
    - npm install
  script:
    - echo "building from src"
    - npm run build
    - echo "building successfull"
  artifacts:
    paths: 
      - ./build