image: node:latest

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - build
  - deploy

before_script:
    - apt-get update -qq && apt-get install
    - echo "packages instaled successfully."

build:
  stage: build
  before_script:
    - yarn global add node-gyp
    - yarn config set cache-folder .yarn
  script:
    - echo "building from src"
    - yarn -v
    - yarn install
    - yarn run build
  artifacts:
    paths: 
      - ./dist