image: node:9.4.0

cache:
  paths:
    - node_modules/
    - .yarn

stages:
  - build
  - deploy

before_script:
    - apt-get update -qq && apt-get install -qy libelf1

build:
  stage: build
  before_script:
    - export PATH=$HOME/.yarn/bin:$PATH
    - npm -v
    # - yarn -v
    # - yarn config set cache-folder .yarn
    # - yarn install
  script:
    - echo "building from src"
    # - yarn -v
    - npm install
    - npm run build
  artifacts:
    paths: 
      - ./dist