image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

before_script:
    - apt-get install yarn
    - echo "yarn instaled successfully."

build:
  stage: build
  script:
    - echo "building from src"
    - yarn -v
    - yarn install
    - yarn run build
  artifacts:
    paths: 
      - ./dist