image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  before-script:
    - sudo apt install yarn
  script:
    - echo "building from src"
    - yarn -v
    - yarn install
    - yarn run build
  path: 
    - ./dist